version: '2'
services:
  mysql:
    env_file: ./.env
    image: mysql:5.7
    ports:
      - 60001:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_HOST_VOLUME_PATH}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  php:
    env_file: ./.env
    build:
      context: docker/images/php-fpm7.0
      args:
        UID: ${HOST_UID}
    volumes:
      - ${SYMFONY_HOST_RELATIVE_APP_PATH}:/var/www/html
#    user: ${HOST_UID}:${HOST_GID}

  apache:
    env_file: ./.env
    build:
      context: docker/images/apache2.4
      args:
        UID: ${HOST_UID}
    ports:
        - ${APPLICATION_WEB_PORT}:80
    environment:
      FPM_HOST: php:9000
      XDEBUG_CONFIG: remote_host=172.22.0.1
    volumes_from:
      - php
    volumes:
      - ${LOGS_DIR}/apache/:/var/log/apache2/
    links:
      - mysql
      - php