easy_admin:
  entities:
    Document:
      class: App\Entity\Document
      form:
        fields:
#          - 'id'
          - { property: 'name', type: 'text', label: 'Nom', icon: 'user' }
          - { property: 'file', type: 'file', label: 'Fichier', icon: 'file' }
